# Generated by Django 3.0.3 on 2020-03-17 14:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10)])),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=25)),
                ('streetname', models.CharField(max_length=150)),
                ('landmark', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('type', models.CharField(blank=True, choices=[('Home', 'Home 7am - 9pm'), ('Office', 'Office 10am - 6pm')], max_length=25)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.UserRegister')),
            ],
            options={
                'db_table': 'tblUserAddress',
            },
        ),
    ]
