# Generated by Django 3.0.3 on 2020-03-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=256)),
                ('ISBN', models.CharField(max_length=256)),
                ('quantity', models.PositiveIntegerField()),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi')], max_length=256)),
                ('type', models.CharField(choices=[('Hardback', 'HardBack'), ('Paperback', 'Paperback')], max_length=256)),
                ('price', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=256)),
                ('published_year', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=350)),
                ('thumb', models.ImageField(blank=True, default='products/default.png', upload_to='products')),
            ],
            options={
                'db_table': 'tblbooks',
            },
        ),
        migrations.CreateModel(
            name='tblAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbladmin',
            },
        ),
    ]
